version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/demo1/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "gradle"
      - "kotlin"
      - "automatic-merge"
      - "demo1"

  - package-ecosystem: "gradle"
    directory: "/demo2/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "gradle"
      - "kotlin"
      - "automatic-merge"
      - "demo2"

  - package-ecosystem: "gradle"
    directory: "/demo3/"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "gradle"
      - "kotlin"
      - "automatic-merge"
      - "demo3"