name: Auto-Merge Test Demo 3

on:
  pull_request:
    paths:
      - 'demo1/**'
      - 'demo2/**'
      - 'demo3/**'
      - '.github/**'
    branches: [ main ]
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}

jobs:
  auto-merge-test-demo-3:
    if: |
      contains(github.event.pull_request.labels.*.name, 'demo3') ||
      contains(github.event.pull_request.labels.*.name, 'automatic-merge')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
      - run: ./gradlew clean build
