name: Test Demo 2

on:
  pull_request:
    paths:
      - 'demo2/**'
      - '.github/**'
    branches: [ main ]

  workflow_dispatch: {}

jobs:
  check-if-test-should-run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.watched_paths.outputs.src }}
    steps:
      - id: watched_paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            src:
            - demo2/**
            - build.gradle.kts
            - settings.gradle.kts
            - gradle/**
      - name: write build should run in env
        run: |
          echo ${{ steps.watched_paths.outputs.src }}
  test-demo-2:
    needs: check-if-test-should-run
    if: ${{ needs.check-if-test-should-run.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo2
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
      - run: ./gradlew clean build
