name: Test Demo 2

on:
  pull_request:
    paths:
      - 'demo2/**'
      - '.github/**'
    branches: [ main ]

  workflow_dispatch: {}

jobs:
  test-demo-2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo1
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
      - run: ./gradlew clean build
